name: error.yml
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  
  workflow_dispatch:  
jobs:
  build:
   strategy:
     matrix:
       node-version: [18, 20] # Define the Node.js versions to test against

   runs-on: ubuntu-latest
   needs: test
   outputs:
     script: ${{ steps.publish-js.outputs.publishing}} #getting the output from publish-js step

   steps:
     - name: Checkout code ## fecting the code ##
       uses: actions/checkout@v3

     - name: Set up Node.js
       uses: actions/setup-node@v3
       with:
        node-version: ${{ matrix.node-version }} # Use the matrix version  

     - name: Install dependencies
       run: npm ci

     - name: Deploy application
       run: npm run build

  