name: matrix
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  
  workflow_dispatch:  
jobs:
  build:
    strategy:
      matrix:
        node-version: [18, 20] # Define the Node.js versions to test against
        operating-system: [ubuntu-latest, windows-latest] # Define the operating systems to test against
    runs-on: ${{ matrix.operating-system }} # Use the matrix operating system
    steps:
      - name: Checkout code ## fecting the code ##
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
         node-version: ${{ matrix.node-version }} # Use the matrix version  

      - name: Install dependencies
        run: npm ci

      - name: Deploy application
        run: npm run build

  